UPDATE 
    TB_CCPIDSCNT
SET 
    END_DATE = DECODE(
        SIGN((NVL(END_DATE, TO_CHAR((ADD_MONTHS(TO_DATE(START_DATE, 'YYYYMMDD'), 36) - 1), 'YYYYMMDD')) - :b0)), 1, :b0,
        END_DATE),
    END_ORD_NO = :b2
WHERE NODE_TYPE = 'S'
  AND NODE_ID = :b3
  AND DC_PLAN_ID IN ('0680', '0964')
  AND END_ORD_NO IS NULL
  
  
  //수정
  
  UPDATE /*+ INDEX(TB_CCPIDSCNT PK_CCPIDSCNT) */
  TB_CCPIDSCNT
SET END_DATE   = DECODE(
      SIGN((NVL(END_DATE, TO_CHAR((ADD_MONTHS(TO_DATE(START_DATE, 'YYYYMMDD'), 36) - 1), 'YYYYMMDD')) - :b0)), 1, :b0,
      END_DATE),
  END_ORD_NO = :b2
WHERE NODE_TYPE = 'S'
AND NODE_ID = :b3
AND DC_PLAN_ID IN ('0680', '0964')
AND END_ORD_NO IS NULL


