SELECT *
	FROM AT_DEPT_STAFF_R T1
	JOIN AT_DEPT_M T2
		ON T1.INST_CD = T2.INST_CD
		AND T1.DEPT_ID = T2.DEPT_ID
	JOIN AT_STAFF_M T3
		ON T3.INST_CD = T2.INST_CD
		AND T3.STAFF_ID = T1.STAFF_ID
	WHERE
		T1.INST_CD = "STDA"
		AND T1.STAFF_ID = "SFINI002"
		
		
		
SELECT 
	T3.INST_CD			AS instCd
	,T3.STAFF_ID		AS staffId
	,T3.ACTOR_ID		AS actorId
	,T3.LOIN_ID_NBR		AS loinIdNbr
	FROM AT_DEPT_STAFF_R T1
		JOIN AT_DEPT_M T2
			ON T1.INST_CD = T2.INST_CD
			AND T1.DEPT_ID = T2.DEPT_CD
		JOIN AT_STAFF_M T3
			ON T3.INST_CD = T2.INST_CD
			AND T3.STAFF_ID = T1.STAFF_ID
		WHERE
			T3.INST_CD = #(instCd)
			AND T3.STAFF_ID = #(staffId)